import React from "react";

function Download({ values }) {
  return (
    <div>
      <h1>
        {values.firstName} &nbsp;
        {values.lastName}
      </h1>
      <table>
        <tr>
          <td>Personal Details:</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.email}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.phoneNumber}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.website}</td>
          <td>{values.linkedin}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.facebook}</td>
          <td>{values.gitHub}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.twitter}</td>
          <td>{values.instagram}</td>
        </tr>
        <tr>
          <td>Educational Details:</td>
          <td>{values.college}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.fromCollegeDate}</td>
          <td>{values.toCollegeDate}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.qualification}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.collegeDesciption}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.school}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.fromSchoolDate}</td>
          <td>{values.toSchoolDate}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.schoolQualification}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.schoolDescription}</td>
        </tr>
        <tr>
          <td>Project Details</td>
          <td>{values.projectOneTitle}</td>
          <td>{values.projectOneLink}</td>
          <td>{values.projectOneDescription}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.projectTwoTitle}</td>
          <td>{values.projectTwoLink}</td>
          <td>{values.projectTwoDescription}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.projectThreeTitle}</td>
          <td>{values.projectThreeLink}</td>
          <td>{values.projectThreeDescription}</td>
        </tr>
        <tr>
          <td>Work Experience:</td>
          <td>{values.experienceOneOrg}</td>
          <td>{values.experienceOnePos}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.experienceOneDur}</td>
          <td>{values.experienceOneDes}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.experienceTwoOrg}</td>
          <td>{values.experienceTwoPos}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.experienceTwoDur}</td>
          <td>{values.experienceTwoDes}</td>
        </tr>
        <tr>
          <td>Skills:</td>
          <td>{values.skill1}</td>
          <td>{values.skill2}</td>
          <td>{values.skill3}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.skill4}</td>
          <td>{values.skill5}</td>
          <td>{values.skill6}</td>
        </tr>
        <tr>
          <td>Interests:</td>
          <td>{values.interest1}</td>
          <td>{values.interest2}</td>
          <td>{values.interest3}</td>
        </tr>
        <tr>
          <td></td>
          <td>{values.interest4}</td>
          <td>{values.interest5}</td>
          <td>{values.interest6}</td>
        </tr>
      </table>
    </div>
  );
}

export default Download;
